name: Deploy to App Engine

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      run: |
        echo "GOOGLE_CLOUD_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
        gcloud config set project $GOOGLE_CLOUD_PROJECT_ID
      shell: bash

    - name: Deploy to App Engine
      if: github.event.pull_request.merged == true
      run: |
        gcloud components install app-engine-go
        gcloud app deploy ./app.yaml --project $GOOGLE_CLOUD_PROJECT_ID --version develop --quiet
      shell: bash