name: Deploy to App Engine

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to App Engine
      if: github.event.pull_request.merged == true
      run: |
        gcloud components install app-engine-go
        gcloud app deploy ./app.yaml --project ${{ secrets.GCP_PROJECT_ID }} --version develop --quiet
