name: Deploy to App Engine

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to App Engine
      run: |
        apt-get install google-cloud-sdk-app-engine-go
        gcloud components install app-engine-go
        gcloud app deploy ./app.yaml --project ${{ secrets.GCP_PROJECT_ID }} --version develop --quiet
      shell: bash