name: Deploy to App Engine

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      matrix:
        include:
          - branch: master
            branch_value: prod
          - branch: develop
            branch_value: dev

    if: matrix.branch == github.event.pull_request.head.ref
    env:
      BRANCH_VALUE: ${{ matrix.branch_value }}

    steps:
      - id: checkout
        name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate timestamp
        id: timestamp
        run: echo "::set-output name=value::$(date +%Y%m%d-%H%M%S)"

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with: #@FIXME: こっちの認証方法は古いらしい
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v1'
        with:
          flags: '--version=${{ env.BRANCH_VALUE }}-${{ steps.timestamp.outputs.value }}'